### ISSUE TITLE
Quick quesiton on the plot in the quick quide

### ISSUE THREAD

**Issue by wox0cdc** [vincent-dk/msgl#6]
HI Martin, I have a brief question on your Quick start document.

To evaluate the models (by different alpha), you have plot 'the Err against the number of features and parameters'. 
My question is that the number of parameters (Xaxis) are from msgl::fit using the *same lambda sequence* used to produce Err (on Yaxis) from msgl.cv? 

It seems a user can only extract Err from msgl.cv, and the info for the model estimate (beta coefficients) can be only extracted from msgl:fit? 

THanks!

**Comment by vincent-dk** [comment]
Hi, take a look at this:
https://github.com/vincent-dk/msgl/blob/develop/plot-cv-results.md

msgl::cv is for cross validation, it fit a number of (sub) models (not using all samples) in order to estimate the error and number of features in the final model. msgl::fit is for fitting the final model (using all the samples) and the result contains no estimate of the error only the final model (beta coefficients).

**Comment by wox0cdc** [comment]
Thank you so much!
I was looking for the command features_stat, parameters_stat from fit.cv.
This is super helpful.

Thanks,
Sunny
